### ISSUE TITLE
Problema instalando Koa

### ISSUE THREAD

**Issue by jmwielandt** [IIC2513-2019-1/syllabus#1]
Hola!

Instalé NodeJS 10.15.3  en mi computador (W10) y siguiendo la guía de instalación de la propia página de Koa

![image](https://user-images.githubusercontent.com/37153467/54764193-0fb33c80-4bd6-11e9-8c0a-40509ba61eb4.png)

![image](https://user-images.githubusercontent.com/37153467/54764170-06c26b00-4bd6-11e9-9937-1bae09e16199.png)

![image](https://user-images.githubusercontent.com/37153467/54764377-6c165c00-4bd6-11e9-9b66-d26464833dcb.png)

¿Esto está funcionando?

Gracias.

PD: google no está cooperando.

**Comment by FarDust** [comment]
Saludos, 

Si Koa no esta instalado en tu versión de node al momento de hacer el `require()` debería mostrarte esto
![image](https://user-images.githubusercontent.com/26115793/54850826-efaf7600-4cc6-11e9-9560-e4fa2a1d49b7.png)

En efecto tienes instado koa en tu PC, el warnig (no un error) que te esta mostrando la consola se debe a que la instalación se realizo en general para todo el PC en vez de una dependencia aparte como es recomendado.

Te dejo este [link ](https://medium.freecodecamp.org/requiring-modules-in-node-js-everything-you-need-to-know-e7fbd119be8)que te podría ser útil para saber como funciona la función` require()`.
