### ISSUE TITLE
Podemos usar bcrypt para hashear las contraseñas?

### ISSUE THREAD

**Issue by eiherrera** [IIC2513-2019-1/syllabus#10]
Hola! 

Como dice el título de la issue, me pregunto si podemos usar [bcrypt](https://www.npmjs.com/package/bcrypt) para hashear las claves. En caso de que no se pueda, o que bien tengan pensado usar otra librería para lograr lo mismo, me gustaría saber cuál/es está/n permitida/s.

Saludos!

**Comment by gpvidal** [comment]
Hola @eiherrera ,

Ningún problema!

Saludos,

**Comment by eiherrera** [comment]
Ok! Gracias!
