### ISSUE TITLE
Convert to an ES6 module

### ISSUE THREAD

**Issue by naquiroz** [IIC2513-2019-1/syllabus#16]
En el `template`, en `index.js`:

```es6
const fs = require('fs');
const path = require('path');
const Sequelize = require('sequelize');
const config = require('../config/database.js')[process.env.NODE_ENV || 'development'];
```

Sin embargo, el editor me da un `Quick Fix` en la línea 1 que me suguiere: `File is a CommonJS module; it may be converted to an ES6 module.ts(80001)`. Al aplicarlo, obtengo:

```es6
import { readdirSync } from 'fs';
import { basename as _basename, join } from 'path';
import Sequelize from 'sequelize';

const config = require('../config/database.js')[process.env.NODE_ENV || 'development'];
```

Y el linter no me tira ningún warning. Puedo dejarlo así (que ademas se ve mas bonito y claro :smile: )?

**Comment by gpvidal** [comment]
Hola @naquiroz !

No creo que hayan sido los únicos cambios que haya aplicado, pero finalmente si todo funciona estaría bien. 

**Ojo eso sí con las sugerencias automáticas** , no siempre son perfectas y probablemente puede romper otras cosas.

Saludos!

**Comment by naquiroz** [comment]
Efectivamente hizo mas cambios, pero para que funcionara :smile: a fin de cuentas el archivo funciona de igual manera. Gracias! :tada:
