### ISSUE TITLE
Sobre Associations

### ISSUE THREAD

**Issue by malopez16** [IIC2513-2019-1/syllabus#17]
Hola!
Después de darle hartas vueltas, he visto tutoriales en los que las asociaciones entre distintas entidades se agregan directamente en el archivo de modelo (lo que no me suena muy bien) y a la vez se realiza una pequeña migración. Lo anterior no me convence porque yo creería que se tendría que hacer todo sólo con migraciones. Estoy muy mal? 
He visto también algunas guías que tienen harto código obsoleto, por lo que aprovecho de preguntar si hay o recomiendan alguna guía que podamos seguir en especial para el establecimiento de asociaciones.

Gracias!

**Comment by gpvidal** [comment]
Hola @malopez16 !

Recuerda que las migraciones son para, en general, "versionar" los cambios en la base de datos. Tu aplicación no puede intuir que tu nuevo campo es para eso ya que podrías tener multiples relaciones a un mismo modelo, por ejemplo, en un post podrías tener la relación de quien lo creó y quien lo editó a un modelo `user` (implicaría dos columnas distintas en la base de datos).

Es por este motivo que debes indicar en el modelo a quién se hace la referencia, porque es parte de la responsabilidad del modelo saber con cuales otros se relaciona.

Una cosa muy similar pasa con otros frameworks como Rails. Tu creas una migración de modelo y, los campos que quieres referenciar, lo creas como `references`. Finalmente en el modelo se escriben los `belong_to`, `has_many`, `has_one`, etc.

Saludos,
