### ISSUE TITLE
Permisos para Heroku

### ISSUE THREAD

**Issue by jedelacarrera** [IIC2513-2019-1/syllabus#18]
Pueden proveer permisos para que heroku pueda hacer deploy directo desde una rama? Para poder configurarlo y que el deploy sea más rápido, en especial para los cambios que se hagan a último minuto.

**Comment by gpvidal** [comment]
Hola @jedelacarrera ,

El permiso que solicita Heroku es para la organización y su información privada, por lo que no vamos a dar acceso dado esto.

Saludos,
