### ISSUE TITLE
No se asignan todos los atributos al crear un recurso

### ISSUE THREAD

**Issue by Pudindin** [IIC2513-2019-1/syllabus#19]
¡Hola!
En el contexto del proyecto, hoy estuve gran parte del día intentado resolver un error que, entre los de mi grupo, no tenemos idea de por qué se genera.
Resulta que, al crear una instancia de una entidad, no se le asignan todos los valores que le pasamos. Si bien al principio se le entregan los atributos desde el html, al momento de llegar al router sólo algunos de estos quedan asignados. En particular, se asignan sólo 2 y los timestamp, mientras que el id y otros dos quedan como nulos, a pesar de haberles dado valores explícitios en el html. 
Por ejemplo, le paso valores A:1, B:2, C:3, D:4 en el html. Pero, luego de crearla, queda: id:null, A:1, B:2, C:null, D:null.
Lo he probado de muchas maneras y he puesto cientos de console.log() para ver lo que pasa, pero no he podido arreglarlo.
Lo atributos que sí se guardan son siempre los mismos. Independiente de si saco uno o ambos, o cambio el orden relativo en que se asignan, el resto quedan como nulos.
Este problema resulta imposibilitar todo, porque para borrar y editar un recurso se utiliza el id. Pero como es nulo, no le puedo hacer nada.
Eso sí, una compañera corrió exactamente el mismo código en su computador, y este problema no ocurrió sino hasta después de editar, borrar y crear un par de instancias. En el mío sucede al primer intento.
Por si acaso, el código es prácticamente el mismo que el que hicimos en clases. Pero corrí el de my-university, y no se me genera ningún error.  Además, al momento de crear el recurso, no se levanta ningún error ni alerta, a pesar de que estos valores queden nulos (y que en el modelo esté explícito que el id no debería ser nulo).
Para rematar, esto pasa para dos entidades distintas. Y aquellas que sí funcionan, tienen un código prácticamente equivalente.
Desde ya, agradezco cualquier ayuda que me puedan brindar. De verdad, ni siquiera sé por qué pasa esto, como para poder arreglarlo. Y menos aún por qué no pasa en los otros casos.
Ayuuuuda

**Comment by gpvidal** [comment]
Hola @Pudindin ,

Podría ser un typo? (tipo *lenght* en vez de *length*) Podrías imprimir en consola el *body* del *request* que llega a tu *router*, para ver dónde están los otros parámetros.

Saludos,

**Comment by Pudindin** [comment]
Hola,
Revisé los tipos de datos, y parece que el problema no está ahí.
Por otro lado, puse que se imprimiera en pantalla el _body_ de la solicitud. No se imprimió nada, como si estuviera vacío. 
Es más, si imprimo ctx.request, muestra el _method_, _url_ y _header_, pero no aparece el _body_. Al parecer, por alguna razón, la solicitud no tiene cuerpo. Busqué cómo solucionar esto, y aunque encontré varias páginas con errores parecidos que se solucionaban con BodyParser, no lo pude implementar de modo que lo arreglara.

**Comment by LuisFros** [comment]
Estas permitiendo todos los atributos del modelo al guardarlo? [await course.save({ fields: ['code', 'name', 'description'] });](https://github.com/IIC2513-2019-1/my-university/blob/2083ead7f577f73ea7ac8b0fd08d40298888d2a8/src/routes/courses.js#L39)

**Comment by gpvidal** [comment]
No, sólo los campos `code`, `name` y `description`

**Comment by LuisFros** [comment]
Perdon, no fue claro mi comentario. Le queria preguntar a @Pudindin  si en su aplicacion el permitio los campos correspondientes a su modelo. 
Puse el ejemplo del template para mostrarle a que linea de codigo me referia.

**Comment by gpvidal** [comment]
Ahhh sorry, yo no me fijé quién había iniciado el comentario :+1: 
Otra pregunta: ¿Versión de Node?

**Comment by Pudindin** [comment]
@LuisFros , ¿a qué te refieres con permitir los atributos?
En el código tengo la línea 'await mientidad.save({ fields: [ ... ] })`, y ahí están explicitados todos los atributos que quiero asignar, incluidos los que no se asignan (y ya revisé varias veces, y están todas bien escritas). No sé si eso es permitirlos, o si falta algo más.
@gpvidal , la versión de nodejs que ocupo es la 10.9.0

**Comment by LuisFros** [comment]
@Pudindin Si, me refieria si estabas explicitando que atributos recibir del form.
Por casualidad, la entidad que te causa el problema fue creada antes de modificar codigo en su Router respectivo o modificar el modelo? (routers/tumodelo.js o models/tumodelo.js)
Tuve un problema similar al modificar codigo, que las entidades creadas (anteriores a los cambios) en mi base de datos local  quedaban con atributos nulos o no podia modificarlos. 
Como estaba en desarollo, decidi limpiar mi base de datos y crear entidades nuevas. Despues de eso, no tuve mas problemas con las entidades creadas.

**Comment by Pudindin** [comment]
@LuisFros , acabo de borrar la base de datos para ver si ese era el problema. Sin embargo, incluso con una BD nueva, las entidades siguen sin guardarse bien y la _request_ sigue sin tener _body_.

Para complementar la descripción del problema, al ejecutar cualquier acción, se imprime en consola la operación SQL correspondiente (SELECT ... ; INSERT INTO .... ; UPDATE ....). Pero, al crear una entidad del tipo en cuestión, la operación INSERT INTO recibe como atributos sólo los que sí se guardan, los otros no. Y el UPDATE también ignora estos últimos (por ejemplo, al actualizar un valor de los que no se asignan, sólo se hace UPDATE a la variable "updatedAt").

**Comment by gpvidal** [comment]
@Pudindin , tenemos algún update? Sigue pasando lo mismo? En qué modelo?

Saludos,

**Comment by Pudindin** [comment]
@gpvidal , hoy estuve un buen rato tratando de arreglarlo y agregar cosas al proyecto, y en eso lo logré solucionar. Resulta que había escrito mal uno de los valores de los `<input>` del html, y por eso no se guardaban los atributos bien. 
Debo reconocer que un error bastante tonto, pero que me costó bastantes horas encontrarlo.  
¡Gracias por la ayuda!
