### ISSUE TITLE
E1 - modelado de datos

### ISSUE THREAD

**Issue by jmwielandt** [IIC2513-2019-1/syllabus#2]
Hola, 
¿Debemos considerar como único posible uso el de DBMS relacionales tipo SQL o podemos usar algo como MongoDB, que ajusta mejor al tipo de problema que enfrentamos? (Re-Z).

Gracias.

**Comment by gpvidal** [comment]
Hola @jmwielandt,

Sí, van a ocupar un base de datos relacional. Me intriga saber tu argumento de por qué MongoDB se ajusta mejor al tipo de problema.

Saludos,
Gabriel

**Comment by jmwielandt** [comment]
Una receta tiene una cantidad variable de ingredientes y pasos a seguir, estos pasos pueden tener una extensión de caracteres muy variable.
También se espera que haya fotos en cantidad variables, por lo que, en mi opinión, usar un modelo relacional para esta problemática (el modelamiento de las recetas, como mínimo) es un despropósito tanto en términos de espacio como de tiempo (eficiencia). Sería tener una cantidad absurdamente alta de relaciones y de gran tamaño, para relativamente pocos datos.

Si aún así esperan que lo hagamos, no hay problema pero este problema nos grita fuertemente "USEN UN MODELO BASADO EN DOCUMENTOS" (JSON).

Saludos.

**Comment by gpvidal** [comment]
@jmwielandt sí queremos que sufran y por eso les colocamos una relacional :joy: 

Ojo que los modelos no-relacionales tampoco son la panacea y la solución a todos los problemas. Tenía curiosidad por saber cuáles son los puntos que veías para decir tan decididamente que es un problema para "no-relacional". Por ejemplo, la extensión de caracteres variable es algo que ya se solucionó hace bastante tiempo en una base de datos relacional, e incluso algunas soluciones ahora tienen campos de tipo JSON en los que se pueden operar.

Finalmente, van a ocupar una base de datos relacional. Ese es el motivo que pedimos un diagrama E/R :wink: 

Saludos,
Gabriel
