### ISSUE TITLE
problema create model

### ISSUE THREAD

**Issue by BeaGaete** [IIC2513-2019-1/syllabus#20]
Hola! tengo el siguiente error al intentar crear el modelo user
![Captura de pantalla 2019-04-13 a la(s) 13 01 49](https://user-images.githubusercontent.com/26144496/56082753-8664e380-5dea-11e9-8017-121163f66d99.png)
Ayuda please

**Comment by Felipehanckes** [comment]
Hola Bea! 

Tuve el mismo error en un principio, el error esta en que sequelize es estricto en la sintaxis y estas separando los distintos atributos con un espacio, tienes que poner el mismo comando pero sin espacios después de las ",".

te quedaría algo así luego de el nombre del modelo;
--attributes firstname:string,secondname:string,photo:string,etc:etc

Ojalá te sirva!

**Comment by BeaGaete** [comment]
Muchas gracias! Resultó :)
