### ISSUE TITLE
Seed para entidades con asociaciones

### ISSUE THREAD

**Issue by acrojas2** [IIC2513-2019-1/syllabus#21]
Hola,
Estamos haciendo seeds para entidades con sus asociaciones, hemos googleado bastante y no nos ha resultado nada. Como se agrega en la seed el atributo "foraneo"?.
Saludos!

**Comment by gpvidal** [comment]
Hola @acrojas2 !

Cuando creas la asociación, `Sequelize` agrega automáticamente algunos métodos para representar estas asociaciones. Aqui lo describe:

http://docs.sequelizejs.com/manual/associations.html#associating-objects

De esta forma puedes:

1. Crear seed para cada modelo
2. Crear una nueva migración y asociarlos en ella.

Saludos,
