### ISSUE TITLE
Problema al correr migraciones

### ISSUE THREAD

**Issue by beayancan** [IIC2513-2019-1/syllabus#22]
Hola.

Resulta que mis compañeros hicieron cambios en el proyecto, al hacer pull y correr las migraciones me aparece el siguiente mensaje `File: .gitkeep does not match pattern: /\.js$/`. Intenté clonando nuevamente el repositorio, pero me aparece el mismo mensaje. Lo extraño es que a ellos les ejecuta bien ¿Alguna idea?

![Captura de pantalla de 2019-04-14 18-54-52](https://user-images.githubusercontent.com/37157874/56100488-46375b00-5ee7-11e9-85a9-45b50cbb3915.png)

Debido a eso, no me reconoce la columna `username` en el modelo de `user`

![Captura de pantalla de 2019-04-14 18-45-17](https://user-images.githubusercontent.com/37157874/56100602-e5a91d80-5ee8-11e9-839c-951d939598e0.png)

**Comment by gpvidal** [comment]
Hola @beayancan ,

Probaste borrando la carpeta `node_modules` y corriendo `yarn install`?

Saludos,

**Comment by beayancan** [comment]
Ya lo pude resolver, el problema era que había corrido una migración que me salió mal, después volví a clonar el repositorio en otro directorio, pero había olvidado el deshacer la migración fallida y no podía resolverlo ya que el archivo no se encontraba.

Al final tan solo debía volver a crear el archivo de la migración fallida que faltaba, correr `db:migrate:undo:all` y borrar la migración que había salido fallida.

```Javascript
// XXXXX-<nombre migración>.js
module.exports = {
  // eslint-disable-next-line no-unused-vars
  up(_queryInterface) {
    return Promise.resolve();
  },

  down() {
    return Promise.resolve();
  },
};
```

**Comment by beayancan** [comment]
Tan solo me queda una duda, el proyecto me funciona sin problemas, tan solo me siuge apareciendo el mensaje `File: .gitkeep does not match pattern: /\.js$/` cuando corro las migraciones. A pesar de eso las migraciones y seeds se corren bien.

![Captura de pantalla de 2019-04-15 15-25-20](https://user-images.githubusercontent.com/37157874/56159792-85bb8100-5f93-11e9-9d4e-b8fcaf23c6c8.png)

**Comment by gpvidal** [comment]
Hola @beayancan !

Eso es normal, es debido a que el comando hace una búsqueda para ver cuáles son migraciones.

Saludos,
