### ISSUE TITLE
Problemas comando sequelize deploy Heroku

### ISSUE THREAD

**Issue by malopez16** [IIC2513-2019-1/syllabus#25]
Hola!
Siguiendo la guía de deploy a Heroku [ de acá ](https://github.com/IIC2513-2019-1/syllabus/issues/23) estoy teniendo un problema al correr los comandos de sequelize:

![image](https://user-images.githubusercontent.com/26126519/56171815-a0eab880-5fb4-11e9-8450-fed5fc8fa210.png)

Se sugiere que se corra el comando
 `heroku run ./node_modules/.bin/sequelize`
con el cual si puedo hacer llamados locales el cuál funciona de manera correcta localmente:
![image](https://user-images.githubusercontent.com/26126519/56171880-02128c00-5fb5-11e9-8186-39266504e807.png)

Pero a la hora de llamarlo a Heroku, no funciona :( , al igual que el anterior:
![image](https://user-images.githubusercontent.com/26126519/56171846-c8da1c00-5fb4-11e9-8ca1-c992be05d037.png)

He estado un par de horas intentando solucionarlo y no he podido lograrlo. 
Estaría infinitamente agradecido si alguien me ayuda.

Edit: Las cosas que he probado, entre muchas:
https://stackoverflow.com/a/50108205

**Comment by eiherrera** [comment]
Hola! A mi me apareció el mismo mensaje cuando seguí el tutorial de la guía, pero una vez que seguí los demas pasos, mi aplicación igual funcionó correctamente. El `bash: sequelize: command not found` no implica que en heroku no está funcionando sequelize, de hecho si no me qeuivoco la línea arriba de ese mensaje te está diciendo que heroku logró ejecutar sequelize.

Saludos!

**Comment by malopez16** [comment]
Buena! finalmente seguí la guía y había otro problema: En el proyecto base hay un package-lock y un yarn al mismo tiempo(??) Lo que hace conflictos. Finalmente eliminé el package lock y corrí los siguientes comandos ignorando lo de sequelize. Luego, al haber hecho up, si me permitió correr esos comandos :)

Saludos y gracias :)

**Comment by gpvidal** [comment]
Hola @malopez16 

Ojo que si tienes un archivo `package-lock.json` implica que alguien de tu grupo (o tu) está usando `npm` y no `yarn`. 

Saludos,
