### ISSUE TITLE
Despliegue de cursos my-university

### ISSUE THREAD

**Issue by beayancan** [IIC2513-2019-1/syllabus#26]
En el ejemplo my-university, se crea la asociacion N:N entre students y courses, generando una vista para los courses de un student, sin embargo, cuando ejecuto my-university para los students no se despliegan los cursos ni viceversa, dice que está vacio.

Además, quería saber ¿De qué forma funciona el metodo getstudents y getcourses que usan en routes de cada uno? Dado que no están antes definidos.

Gracias.

**Comment by gpvidal** [comment]
Hola @beayancan !

Para que existan estudiantes en la aplicación, debes correr la siguiente migración:
https://github.com/IIC2513-2019-1/my-university/commit/9308679fb0416e957542e90cf24afa3a4e0fa0c6#diff-41c5276744036808fac205b30b7b157c

Y luego, para agregar alumnos al curso, debes correr esta otra migración:
https://github.com/IIC2513-2019-1/my-university/commit/9308679fb0416e957542e90cf24afa3a4e0fa0c6#diff-16bf2e99f74b8ea73d69cc585a4f5c55

Con esto debería aparecerte información en ambas secciones.

Con respecto a los métodos `getStudents` y `getCourses` son métodos creados por Sequelize debido a las relaciones que están declaradas en los modelos. Puedes encontrar la información aquí:

http://docs.sequelizejs.com/manual/associations.html#associating-objects

Saludos!
