### ISSUE TITLE
Formas de garantizar email único.

### ISSUE THREAD

**Issue by chapito96** [IIC2513-2019-1/syllabus#27]
Hola, en el ejemplo de my-university para garantizar un mail único se realiza de dos formas distintas. En el caso de "user" se crea una nueva migración en que se agrega un Constraint, se le agrega un nombre a esa restricción y luego se llama en el modelo en las validaciones del email.
En el caso de "student" se crea un índice directamente en la migración que crea la tabla "students" y luego en el modelo de "student" se llama a dicho indice en las validaciones de email.
¿Cual es la diferencia/ventajas/desventajas de estos dos métodos? ¿Hacen lo mismo?

Gracias de antemano!

**Comment by gpvidal** [comment]
Hola @chapito96 ,

La verdad es que son dos maneras de lograr lo mismo. En uno lo haces en una migración distinta y en el otro en una misma migración.

Saludos,

**Comment by chapito96** [comment]
Ligado al mismo tema, que uno lo haga generando un índice y el otro un "constrain" es un tema de nombre? ¿o a nivel de base de datos funciona diferente?

**Comment by gpvidal** [comment]
Tienen opciones diferentes (aunque ambas para este caso funcionan igual), mira aquí:

* `addIndex:` http://docs.sequelizejs.com/class/lib/query-interface.js~QueryInterface.html#instance-method-addIndex
*  `addConstraint:` http://docs.sequelizejs.com/class/lib/query-interface.js~QueryInterface.html#instance-method-addConstraint

**Comment by chapito96** [comment]
Muchas gracias!
