### ISSUE TITLE
Uso Cloudinary para manejo de imagenes en heroku

### ISSUE THREAD

**Issue by Felipehanckes** [IIC2513-2019-1/syllabus#28]
Estimados, 

Dado que Heroku no soporta de buena forma las imagenes, se puede utilizar Cloudinary para manejar las imagenes dentro de la aplicación :grey_question:  

De no ser posible, que otros add-ons de heroku podrían ser utiles o no podemos usar addons:grey_question:

**Comment by gpvidal** [comment]
Hola @Felipehanckes ,

Sí, pueden ocupar ese storage. Deben ver eso sí como subir las imágenes, porque no sé si está soportado por `pkgcloud` (que fue la herramienta que vimos). Pero me di cuenta que Cloudinary tiene SDK propio.

Saludos,

**Comment by Felipehanckes** [comment]
Perfecto, y herramientas como Multer también están permitidas?

**Comment by gpvidal** [comment]
Este multer? https://github.com/expressjs/multer 

Si es así, y tal como vimos en clases, el template ya cuenta con uno incorporado. Si lo quieren cambiar lo pueden hacer, pero ustedes deben lidiar con el cambio.

Saludos,
