### ISSUE TITLE
.routes is not a function 

### ISSUE THREAD

**Issue by francisca1** [IIC2513-2019-1/syllabus#29]
hola! estaba creando la entidad comments con todos sus atributos, controlador, etc, sin embargo cuando hago yarn start me dice esto:
![imagen](https://user-images.githubusercontent.com/26394880/56936256-732d6580-6ac4-11e9-9251-d3bd96802900.png)
esta es mi configuacion de routes:
![imagen](https://user-images.githubusercontent.com/26394880/56936269-88a28f80-6ac4-11e9-9545-2bd571443833.png)
no entiendo que es lo que tengo mal, gracias!

**Comment by gpvidal** [comment]
Hola @francisca1 ,

Lo que se me ocurre es que en tu archivo `./routes/comments` no esté (al final) la línea `module.exports = router;` ¿Puede ser?

Saludos,

**Comment by francisca1** [comment]
Efectivamente, era eso, gracias.
