### ISSUE TITLE
Idioma variables y código en general

### ISSUE THREAD

**Issue by jmwielandt** [IIC2513-2019-1/syllabus#3]
Hola, 
¿Existe algún problema por llamar a nuestras variables, atributos y demás en español y no en inglés?

Pensé que quizás querían descontarnos por eso :cry: (espero no estar dándoles la idea).
Gracias.

**Comment by gpvidal** [comment]
Hola @jmwielandt !

De las [recomendaciones](https://github.com/IIC2513-2019-1/syllabus/tree/master/proyecto#recomendaciones) del proyecto: 

> Escriban su código en inglés. Sacarán el máximo provecho de las convenciones que puedan haber y su código quedará en armonía con el lenguaje de programación que usen (que también estará en inglés). La interfaz de su aplicación puede estar en inglés o en español.

No hay descuento, pero nosotros recomendamos seguir esta regla fuertemente.

Saludos,
