### ISSUE TITLE
¿Sequelize v5?

### ISSUE THREAD

**Issue by jmwielandt** [IIC2513-2019-1/syllabus#30]
Hola, entré a la [página de sequelize](http://docs.sequelizejs.com/manual/upgrade-to-v5.html) y descubrí que la versión 5 está desde el 13 de marzo de este año, pero en nuestros proyectos estamos con la 4.6.algo. ¿Qué tan importante es que nos actualicemos?

Gracias.

**EDT:** viendo  el yarn.lock, tenemos:
```
sequelize@^4.6.0:
  version "4.38.0"
  resolved "https://registry.yarnpkg.com/sequelize/-/sequelize-4.38.0.tgz#330c1aa445d4e46b80a97d895603c01666cdc357"
```

**Comment by gpvidal** [comment]
Hola @jmwielandt ,

Por ahora no es relevante, además tiene unos breaking changes que aún no he revisado que impacto tienen. Así que, dado que es un release de major version (de 4 a 5) por el momento mantengan la versión que venía en el template.

Saludos,

PD: Mirando rápidamente, desaparece el `findById`
