### ISSUE TITLE
digitaloceanspaces Cobra D: 

### ISSUE THREAD

**Issue by Arcoirisky** [IIC2513-2019-1/syllabus#31]
Hola!

En clases, para subir cosas a la nube vimos que teníamos que inscribirnos en la pag de digitaloceanspacer para poder hacerlo pero cuando me estoy inscribiendo me pide una tarjeta de credito D: ¿esto es correcto o me metí a cualquier sitio random? ;----;

**Comment by gpvidal** [comment]
Hola @Arcoirisky !

No es que tengan que inscribirse en esa página en particular, pueden escoger cualquier cloud storage de cualquier proveedor. Efectivamente DigitalOcean pide tarjeta de crédito para crear una cuenta.

Hace un poco @Felipehanckes sugirió usar otro acá #28 , y existen otras alternativas. Puedes consultarle a tu ayudante, ya que ellos también tuvieron que implementarlo.

Saludos!

**Comment by Arcoirisky** [comment]
Al final, entre el pánico, descubrí que github, por ser estudiante, te da 50 dólares para digotaloceanspace y como no lo usamos seguido conviene demasiado ya que cobra por hora utilizada al mes :+1:

**Comment by gpvidal** [comment]
Super! Gracias por compartir la info!
