### ISSUE TITLE
Podemos usar el componente react-modal?

### ISSUE THREAD

**Issue by eiherrera** [IIC2513-2019-1/syllabus#36]
Hola! 

Dado que estamos aprendiendo React, me preguntaba si podemos usar componentes ya implementados, como por ejemplo [react-modal](https://github.com/reactjs/react-modal).

Saludos!

**Comment by gpvidal** [comment]
Hola @eiherrera !

Ese particularmente no, pero podrías implementar uno similar :+1: 

Saludos,
