### ISSUE TITLE
Importar script en template

### ISSUE THREAD

**Issue by francisca1** [IIC2513-2019-1/syllabus#37]
Hola! estaba intentanto importar un script para usarlo en cierta vista (lo importo en layout), sin embargo no me funciona, probé de mil maneras y no funcionó.
Como debería hacerlo?donde guardo los scripts?
Se que se dijo en clases, pero no lo anoté.
Gracias.

**Comment by gpvidal** [comment]
Hola @francisca1 !

Puedes, dentro de assets, crear una carpeta para tus códigos Javascript; agregar los archivos a `/src/assets/js/assets.js` y luego usar la función `assetsPath` (como se hacía con el logo) para importarlo.

Saludos,

**Comment by gpvidal** [comment]
Ver ejemplo aquí: https://github.com/IIC2513-2019-1/my-university/pull/10
