### ISSUE TITLE
Problema con mailing al crear usuario

### ISSUE THREAD

**Issue by fernddevidts** [IIC2513-2019-1/syllabus#38]
Hola, 
Estaba tratando de enviar un mail cuando se crea un nuevo usuario, pero no se está ejecutando la función en signup-alert.js. Puse console.logs y me di cuenta de que no se ejecuta esta línea:
return ctx.sendMail('signup-alert', { to: user.email, subject: 'Alert!' }, { user });
que está dentro de module.exports=function sendSignUpAlertEmail.
La estoy llamando en routes/users.js en user.create, después de hacer user.save() con await sendSignupAlertEmail(ctx, { user });
Probé cambiando mails (tanto del to como del from) y no sé que estoy haciendo mal porque no me tira un error específico, solo no se ejecuta.
Gracias!

**Comment by gpvidal** [comment]
Hola @fernddevidts ,

Se me ocurre que podrías estar importándola como:

```js
const { sendSignUpAlertEmail } = require([...])
```

Cuando debería ser:

```js
const sendSignUpAlertEmail = require([...])
```

Podría ser eso?

Saludos,

**Comment by fernddevidts** [comment]
Pucha, no. Está importada sin los { } :(

**Comment by gpvidal** [comment]
Yap, entonces entra al método pero no envía el correo, verdad?

Lo otro es que no tengas bien configurado el envío de correos. Lo estás usando con Sendgrid?

**Comment by fernddevidts** [comment]
Sí, entra pero no ejecuta el ctx.sendMail. Puse SendGrid en services/email.js
Ahora me di cuenta de que llama a variables de ENV y eso no lo he cambiado. Puede ser eso?

**Comment by gpvidal** [comment]
Sí! Tienes que configurarlas con tus datos!

**Comment by fernddevidts** [comment]
Ay que pava, gracias jajaja

**Comment by gpvidal** [comment]
Yo tampoco lo vi en un principio :stuck_out_tongue:
