### ISSUE TITLE
select input para form

### ISSUE THREAD

**Issue by francisca1** [IIC2513-2019-1/syllabus#39]
Buenas, estaba haciendo que los valores de algunos atributos de los forms fueran con valores de select (aquí un ejemplo)
![imagen](https://user-images.githubusercontent.com/26394880/57825182-c4e41a00-776b-11e9-8172-96693a7b309e.png)
y al crear la entidad, esta se crea correctamente, sin embargo cuando edito la publicación (utiliza el mismo form), este valor se me va a null, no entiendo por qué.
Que estoy haciendo mal? 
Gracias.

**Comment by gpvidal** [comment]
Hola @francisca1 ,

Ojo que debería ser:
```html
<select name="continent" value="<%= publication.contient %>">
```
(Sin el espacio entre el igual y el value)

¿Cuál es el valor de `publication.contient` al editar? Si es `null`, Se guarda correctamente?

Saludos,

**Comment by francisca1** [comment]
Efectivamente el problema era el espacio, muchas gracias.
