### ISSUE TITLE
Creación o búsqueda de bases de datos

### ISSUE THREAD

**Issue by Arcoirisky** [IIC2513-2019-1/syllabus#4]
Hola!

Quería entender bien si se desea que nosotros creemos nuestras propias bases de datos para los problemas escogidos o las debemos buscar y utilizar como nos parezca conveniente. Me refiero a buscarlas y limpiarlas de forma que se vuelvan como "la base de datos que soñamos tener".

**Comment by gpvidal** [comment]
Hola @Arcoirisky !

Para la entrega, ustedes tienen que diseñar su base de datos acorde al problema escogido. Cuando comiencen a implementar, pueden buscar datos reales en otras bases de datos e integrarlas a la suya.

Saludos,
