### ISSUE TITLE
Sequalize.array en una tabla

### ISSUE THREAD

**Issue by jvlara** [IIC2513-2019-1/syllabus#40]
¿Existe la manera de que un atributo de una tabla sea un array? busque y encontré algo pero aun así la migración me tira error y no lo logro hacer funcionar :c.

**Comment by gpvidal** [comment]
Hola @jvlara ,

Estuve [revisando](https://github.com/sequelize/sequelize/blob/4478d74a3e5dc8cd30837d8a193754867d06ccf5/lib/dialects/postgres/data-types.js) los tipos para Postgres en Sequelize v4 y no aparece. Esto podría ser algo que se agregó en Sequelize 5.

Saludos,
