### ISSUE TITLE
Funcion assetPath(path)

### ISSUE THREAD

**Issue by cdlepe** [IIC2513-2019-1/syllabus#41]
Hola! 
Quería saber como está configurada la función assetPath(path), ya que intento hacer referencia a una imagen que esta en assets/images y me dice que no la encuentra. Hasta el momento noté que solo encuentra la imagen logo.png que de hecho la saque de la carpeta images y aún así la encuentra, por lo que intuyo que la función assetPath(path) no está haciendo referencia a esta carpeta.
Entonces quería saber como arreglar esta función (o que funcione correctamente) o como hacer para poner imagenes que estén la carpeta assets/images ya que tampoco me resulta poniendo directamente el path "../assets/images/<nombre_imagen>"

**Comment by MrEarle** [comment]
Prueba poniendo `import '../images/<nombre_imagen>'` en assets/js/assets.js
Eso me funciono a mi

**Comment by gpvidal** [comment]
Hola @cdlepe !

Es exactamente lo que dice @MrEarle :+1: 

Saludos!
