### ISSUE TITLE
Podemos usar un componente de react para renderear markdown?

### ISSUE THREAD

**Issue by eiherrera** [IIC2513-2019-1/syllabus#42]
Me gustaría poder usar algo como [react-markdown](https://github.com/rexxars/react-markdown) en el proyecto.

Saludos!

**Comment by gpvidal** [comment]
Hola @eiherrera !

Sí lo puedes ocupar, siempre y cuando sea para hacer render de algo que el usuario ingresó, y no para estilar una página completa.

Saludos,

**Comment by eiherrera** [comment]
Perfect, gracias! Y podemos usar [simplebar](https://github.com/Grsmto/simplebar) para tener una scrollbar mas bonita?

Saludos!

**Comment by gpvidal** [comment]
No, `simplebar` no.

Saludos,

**Comment by eiherrera** [comment]
Perdón que hinche pero, ¿por qué no podemos? Tengo un elemento en html al cual quiero aplicar `overflow-y: scroll`, pero por lo que he visto la scrollbar no se puede estilar en firefox, y la que viene por default arruina la estética de la página. ¿Existe otra alternativa que sí podamos usar?

**Comment by gpvidal** [comment]
Hola @eiherrera ,

Pero entonces ¿Por qué diseñar una estética que se ve bien sólo en algunos navegadores? Efectivamente lo que se ocupa tiene un vendor especificado `-webkit`, por lo tanto aún no es parte del estándar.

Ahora, siempre puedes mirar el CSS de `simplebar` y tomar lo que necesites (citándolo claramente).

> ¿Existe otra alternativa que sí podamos usar?
Para estilar barras no.

Saludos,
