### ISSUE TITLE
Tags permitidos

### ISSUE THREAD

**Issue by jedelacarrera** [IIC2513-2019-1/syllabus#43]
La idea del HTML es tener la estructura mientras que el CSS el estilo, pero no me queda claro cuáles de los siguientes tags debería evitar
```
<b>
<i>
<span>
<small>
<strong>
<em>
<br>
```

**Comment by gpvidal** [comment]
Hola @jedelacarrera !

La regla general es cualquier tag que cambie la apariencia porque, tal como tu dices, el estilo lo ve CSS.
De tu lista todos pueden ser reemplazados por una propiedad de CSS.

Saludos,

**Comment by jedelacarrera** [comment]
¿El span también? ¿Como hago para reemplazar ese tag? O para agregarle estilo a una parte específica dentro de un <p>

**Comment by gpvidal** [comment]
Ahh sorry! ese no. Ese es de estructura :stuck_out_tongue:
