### ISSUE TITLE
Heroku no encuentra los assets

### ISSUE THREAD

**Issue by eiherrera** [IIC2513-2019-1/syllabus#44]
Hola!

De manera local me funcionan perfecto los assets, pero al hacer deploy la aplicación no cuenta con css ni javascript. Revisé `layout.html.ejs` y si tiene la línea `<script src="<%= assetPath('app.js') %>"></script>`, por lo que no es que no haga el llamado a los assets. Al revisar los logs de heroku me aparece lo siguiente: 
![heroku_things](https://user-images.githubusercontent.com/13739349/58199180-eb3f1380-7c9d-11e9-8d34-a6c72e0039b4.png)
¿Alguna idea de porqué heroku no encuentra los assets?

Saludos!

**Comment by gpvidal** [comment]
Hola @eiherrera ,

Las últimas 3 veces que me han preguntado eso es porque han eliminado lineas que venían en el template. Creo que podrías partir revisando por ahí.

Saludos,

**Comment by eiherrera** [comment]
Efectivamente, tenía una línea comentada en `assets.js`.

Gracias!
