### ISSUE TITLE
Error 500 - http://iic2513.phobos.cl:8000

### ISSUE THREAD

**Issue by MarceloSaldias** [IIC2513-2019-1/syllabus#45]
Quería entrar para ver los jupyter con los ejercicios de clase pero me muestra el siguiente mensaje:

> 500 : Internal Server Error
> Spawner failed to start [status=1]. The logs for marcelosaldias may contain details.
> You can try restarting your server from the home page.

Hay algo que se pueda hacer? 😢

**Comment by gpvidal** [comment]
Hola @MarceloSaldias,

Puedes probar ahora?

Saludos

**Comment by MarceloSaldias** [comment]
Hola!

Ahora me sale esto :c

> 500 : Internal Server Error
> Failed to reach your server. Please try again later. Contact admin if the issue persists.
> You can try restarting your server from the home page.

**Comment by gpvidal** [comment]
Y si actualizas ahora? :)

**Comment by MarceloSaldias** [comment]
Ahora si!
Muchas gracias! 😄
