### ISSUE TITLE
react

### ISSUE THREAD

**Issue by francisca1** [IIC2513-2019-1/syllabus#46]
Hola! estaba haciendo un form con react y ya que uso el mismo form para editar y para hacer una nueva entidad, tengo la duda de como puedo pasarle un objeto a un componente react?
este es mi componente:
![imagen](https://user-images.githubusercontent.com/26394880/58531144-4ea1d780-81af-11e9-8e72-ae32760c4e2b.png)
y quiero retornar algo así:
![imagen](https://user-images.githubusercontent.com/26394880/58531205-89a40b00-81af-11e9-8cf4-4fd482a3f0ba.png)
Donde publication es el objeto que le deseo pasar.
Gracias!

**Comment by gpvidal** [comment]
Hola  @francisca1 

Si le quieres pasar un objeto puedes obtenerlo desde tu backend como lo vimos en clases (cuando obtuvimos los cursos) usando `ctx.accepts()`.

Saludos,

**Comment by francisca1** [comment]
entiendo lo que se hace ahí, sin embago si quiero llamar una ruta como publications/:id
necesito tener este parámetro dentro del componente react, como podría hacerse esto?
Gracias.

**Comment by gpvidal** [comment]
Ah, eso lo puedes pasar como un parámetro del dataset (propiedad `data-publication-id="2") en tu HTML y luego leerlo en tu componente.

Saludos,

**Comment by francisca1** [comment]
Muchas gracias! Justo había encontrado algo que era parecido.
Saludos.

**Comment by gpvidal** [comment]
Súper!
