### ISSUE TITLE
error en código de clase react-post

### ISSUE THREAD

**Issue by rihanuch** [IIC2513-2019-1/syllabus#47]
Hola!

Estaba probando utilizar el código que está publicado en el syllabus para probar algo con React y me di cuenta que el código que está publicado (container/post.jsx, Component/post.jsx y services/post.js) tiene un error 

<img width="1283" alt="Captura de pantalla 2019-05-29 a la(s) 11 38 31" src="https://user-images.githubusercontent.com/26392931/58570619-4f198d00-8206-11e9-911a-b3ac312779b1.png">

**Comment by gpvidal** [comment]
Hola @rihanuch ,

Sólo lo colocaste y te mostró eso?

Saludos,

**Comment by gpvidal** [comment]
Se me ocurrió que puede que estés cargando el *dumb* component en vez del *smart*. Puedes revisar eso?

Saludos,

**Comment by rihanuch** [comment]
Creo que faltaban definir los PrppTypesa al final!

Perdón por la demora! Al final use un template de lista😅

Gracias!
