### ISSUE TITLE
script tag's "src" no funciona

### ISSUE THREAD

**Issue by jmwielandt** [IIC2513-2019-1/syllabus#48]
Hola!

Estoy intentando hacer cosas con jquery poniéndolas en su propio archivo `.js` pero estoy teniendo un problema. No importa como ponga el path, no consigo que `<script src="path/al/archivo.js"></script> funcione adecuadamente. El navegador constantemente dice "not found". :(

¿Dónde va el archivo? ¿Y qué path uso? 

Gracias.

**Comment by gpvidal** [comment]
Hola @jmwielandt ,

Te recomiendo revisar este PR de nuestro proyecto de ejemplo, dónde se hizo una inclusión de código del lado del cliente:

https://github.com/IIC2513-2019-1/my-university/pull/10

En ese PR se escribe el código y este es automáticamente incluído, por lo que no es necesario especificar rutas.

Saludos,

**Comment by jmwielandt** [comment]
muchas gracias! :D
