### ISSUE TITLE
Casos de uso

### ISSUE THREAD

**Issue by jmopaso** [IIC2513-2019-1/syllabus#5]
Hola!

Tengo la siguiente duda con respecto a lo que se espera que coloquemos en los casos de uso. ¿Bastaría solo nombrar los casos de uso de nuestra aplicación?, como por ejemplo:
```
1. Registrar asistencia
2. Crear Post
...
```
¿o se espera también que especifiquemos el flujo de cada caso de uso?, por ejemplo:
```
Crear Post:
1a. Usuario no se ha registrado en la aplicación
1a1 Sustema le indica que debe registrarse
1a2 Se registra nuevo ciclista

...

7 El sistema le da la opción de crear post 
7a Usuario crea Post
```

**Comment by gpvidal** [comment]
Hola @jmopaso ,

La idea es que en esta primera entrega a nosotros nos quede claro que entendiste el enunciado. Para los casos de uso no es necesario tanto detalle. Si es importante que tenga un título, el actor y una pequeña descripción. También es relevante que se debe detectar aquellos que son importantes para tu problema.

Saludos,
