### ISSUE TITLE
Redirigir con react

### ISSUE THREAD

**Issue by CmPoblete** [IIC2513-2019-1/syllabus#50]
Hola, como puedo hacer redirecciones en mi pagina usando react?

**Comment by gpvidal** [comment]
Hola @CmPoblete ,

Redirigir en qué sentido? Siempre puedes agregar un link (tag `a`) o no es eso lo que quieres hacer?

Saludos,

**Comment by Pipelao** [comment]
Hola @gpvidal,

Tengo una pregunta similar. Lo que pasa es que en el html uno tiene acceso a por ejemplo coursePath(Course) pero no en react o a menos yo no sé usarlo, ¿de qué manera puedo colocar este link en react?

Gracias de ante mano

**Comment by gpvidal** [comment]
Hola @Pipelao ,

Puedes pasarle al componente React esa URL a través del `dataset` :wink: 

Saludos,

**Comment by Pipelao** [comment]
Profe @gpvidal, se me había olvidado agradecerle, al final coloqué el link en un <a> 😀

**Comment by gpvidal** [comment]
:+1:
