### ISSUE TITLE
ES-Lint - un archivo que no existe y venía en el proyecto

### ISSUE THREAD

**Issue by jmwielandt** [IIC2513-2019-1/syllabus#51]
Hola,
Esto venía en el proyecto pero el linter lleva desde el inicio llorando porque no existe.
![image](https://user-images.githubusercontent.com/37153467/58767691-3938fe80-855d-11e9-9a3f-a54114b7981b.png)

¿Lo dejo así o hay algún paso que nos faltó y ahí está el problema?
Gracias.

**Comment by gpvidal** [comment]
Hola @jmwielandt !

No viene, pero se construye cada vez que hacen `yarn build`. Voy a explicar esto en la siguiente clase para que quede más claro :wink: 

Saludos,
