### ISSUE TITLE
currentUser en React?

### ISSUE THREAD

**Issue by fernddevidts** [IIC2513-2019-1/syllabus#53]
Hola,
¿existe alguna forma de obtener el currentUser (el que está logged in) en el componente React? 
Así como para usarlo en un if como estábamos usándolo en los archivos html.ejs.
Gracias!

**Comment by gpvidal** [comment]
Hola @fernddevidts ,

Sí, hay un par de opciones como pasarle el `id` del usuario actual (por medio del `dataset`) y obtenerlo en tu componente o hacer una ruta que sirva para obtener el usuario actual (por ej: `GET /users/me`) y también obtenerlo en tu componente.

Saludos,
