### ISSUE TITLE
librearia kitsu para manejar JSON:API

### ISSUE THREAD

**Issue by naquiroz** [IIC2513-2019-1/syllabus#54]
Hola, ¿ se puede usa la librería [Kitsu](https://github.com/wopian/kitsu/tree/master/packages/kitsu) para manejara las serializaciones?.

La razón de usar esta libreria y no [`json-api-serializer`](https://github.com/SeyZ/jsonapi-serializer), es que el nivel de documentación para la segunda es muy baja, y además la mantención de la librería es pobre. Por ejemplo, en la segunda no se especifica como agregar atributos en la serialización, que estén basados en funciones.

**Comment by gpvidal** [comment]
Hola @naquiroz ,

Creo que tienes una pequeña confusión. Lo que hace `kitsu` es ser un cliente de API con formato JSON:API, no serializar a una salida JSON:API. Qué es exactamente lo que quieres hacer?

Saludos,

**Comment by naquiroz** [comment]
Hola profesor, gracias por la pronta respuesta. Tiene razón `Kitsu` es un cliente de API, nu un serializador. La verdad  busco un serializador que esté bien documentado nada mas.

**Comment by naquiroz** [comment]
Tambien me gustaría saber como serializar `accessors` que retornan promesas.

**Comment by gpvidal** [comment]
> Hola profesor, gracias por la pronta respuesta. Tiene razón `Kitsu` es un cliente de API, nu un serializador. La verdad busco un serializador que esté bien documentado nada mas.

Hay que seguir buscando entonces si no quieres ocupar el que vimos.

> Tambien me gustaría saber como serializar accessors que retornan promesas.

Una respuesta JSON no puede tener promesas, son resueltas antes de que el servidor responda. A eso te refieres?

**Comment by naquiroz** [comment]
Si, a eso me refiero, entonces hay que hacer un await antes de serializar?

**Comment by gpvidal** [comment]
Si requieres esperar para obtener datos, sí debes hacer un await para obtener esos datos antes de pasarlos por el "serializador".

**Comment by naquiroz** [comment]
Gracias!
