### ISSUE TITLE
Puedo usar reac-spinners-kit para usar loading spinners en react

### ISSUE THREAD

**Issue by naquiroz** [IIC2513-2019-1/syllabus#57]
Encontré [esta página](https://reactjsexample.com/a-collection-of-loading-spinners-with-react-js-2/) que utilizan una libreria llamada `react-spinners-kit` para usar spinners de manera fácil. Podemos utilizarla?

**Comment by gpvidal** [comment]
Hola @naquiroz ,

Sí, si lo pueden utilizar.

Saludos,
