### ISSUE TITLE
Uso de Owl Carousel 2

### ISSUE THREAD

**Issue by lily416** [IIC2513-2019-1/syllabus#58]
Hola,

¿Se puede utilizar [Owl Carousel 2](https://owlcarousel2.github.io/OwlCarousel2/) para hacer la animación de carrucel de un conjunto de imágenes o elementos?

**Comment by gpvidal** [comment]
Hola @lily416 ,

No pueden ocuparlo, pero puedes hacer tu propia implemnetación :wink: 

Saludos,
