### ISSUE TITLE
JWT generator

### ISSUE THREAD

**Issue by smargozzini** [IIC2513-2019-1/syllabus#59]
Tengo un error con la funcion jwtgenerator.sign(). (si entra al if)
```
if (user && await user.checkPassword(password)) {
    const token = await new Promise((resolve, reject) => {
      jwtgenerator.sign(
        { userId: user.id },
        process.env.JWT_SECRET,
        (err, tokenResult) => (err ? reject(err) : resolve(tokenResult)),
      );
    });
    console.log(token)
    ctx.body = { token };
```
me tira un error como  Error: secretOrPrivateKey must have a value. Levo harto tratando de saber porque es, algún consejo?
saludos

**Comment by kenzoak** [comment]
Hola! tengo el mismo problema, pudiste solucionarlo?

**Comment by gpvidal** [comment]
Hola @kenzoak ,

Probablemente no has agregado un valor a la variable de entorno `JWT_SECRET`

Saludos,

**Comment by smargozzini** [comment]
Si, eso era

**Comment by kenzoak** [comment]
Gracias!
