### ISSUE TITLE
Podemos usar node-google-calendar

### ISSUE THREAD

**Issue by diegoheg** [IIC2513-2019-1/syllabus#60]
¿Podemos hacer uso de node-google-calendar para hacer manejo de la api de google calendar?

**Comment by gpvidal** [comment]
Hola @diegoheg ,

Sí, siempre y cuando no quieras reemplazar el consumir una API como lo pide el enunciado de la entrega. Para esto no pueden utlizar un sdk o algo similar, deben hacer el request directo.

Saludos,
