### ISSUE TITLE
Contenidos Examen

### ISSUE THREAD

**Issue by joseluishaddad** [IIC2513-2019-1/syllabus#61]
Hola!
No pude asistir a la última clase y quisiera saber si en el examen serán preguntadas también las cosas "adicionales" que vimos las últimas clases del curso como PWA entre otras o si los contenidos llegarán hasta React y APIs.
Gracias de antemano!

**Comment by gpvidal** [comment]
Hola @joseluishaddad 

Sí, se preguntarán.

Saludos,

**Comment by joseluishaddad** [comment]
Perfecto! Muchas gracias por la rápida respuesta.

**Comment by sofiapacheco1** [comment]
Hola! A qué hora va a ser el examen? Gracias!

**Comment by gpvidal** [comment]
Hola @sofiapacheco1,

A las 9 AM.

Saludos,

**Comment by jmwielandt** [comment]
Hola, 
El examen va a ser examen (materia de todo el semestre pero sin énfasis en ninguna materia), I4 (principalmente la materia vista desde la I3) o una mezcla (todo el semestre pero con énfasis en lo nuevo)??
Gracias

@gpvidal reabriría la issue pero no tengo poderes :(

**Comment by gpvidal** [comment]
Hola @jmwielandt ,

El examen es examen (según tu definición) :+1:  

Saludos,

**Comment by jmwielandt** [comment]
Gracias~
