### ISSUE TITLE
Horario presentación

### ISSUE THREAD

**Issue by NachoCasta** [IIC2513-2019-1/syllabus#63]
Hola!

Estamos inscritos para el Jueves a las 10:30 pero yo tengo un examen a las 9:00 (pense que era a las 8:30), por lo que no estoy seguro de alcanzar a llegar. Será posible presentar al final de todos los grupos o a algún otro horario?

Todos los horarios que quedan son durante mi examen.

Nuestro grupo se llama grupo-webos

Saludos y de antemano gracias!

**Comment by gpvidal** [comment]
Hola @NachoCasta ,

Ninguna opción, dado que los horarios fueron publicados hace un tiempo. La alternativa que tienes es hacerle un cambio a otro grupo.

Saludos,

**Comment by NachoCasta** [comment]
Eso estaba intentando pero me acaban de decir también que el examen durará 3 horas 🙃 por lo que terminará a las 12:00. Ninguna posibilidad de poder presentar a las 12:00?
Si se que era mi responsabilidad haberlo visto de antes pero si no tendría que salirme 1:30 antes de que termine el examen 😰.

Gracias!

**Comment by NachoCasta** [comment]
Al final logré cambiar con otro grupo. En verdad ellos presentaron hoy según lo que me dijeron (BaconSquad) así que su horario mañana va a estar desocupado, que es a las 11:30.

Nos vemos!

**Comment by gpvidal** [comment]
Perfecto! Lamentablemente no podía después de las 12 por diversas reuniones.

Saludos,
