### ISSUE TITLE
Phobos caido

### ISSUE THREAD

**Issue by naquiroz** [IIC2513-2019-1/syllabus#7]
Hola! Estoy tratando de conectarme a la pagina del curso de phobos (http://iic2513.phobos.cl:8000) para estudiar para la prueba, sin embargo me está arrojando `Internal Server Error`, podrían levantarla para ver los archivos? Saludos.

**Comment by gpvidal** [comment]
Hola!

Ya está ok. Te recuerdo que además los archivos y las soluciones están en este repositorio.

Saludos,
