### ISSUE TITLE
Problema con postgresql

### ISSUE THREAD

**Issue by jvlara** [IIC2513-2019-1/syllabus#9]
Al seguir las instrucciones del repositorio de mi grupo no se que hacer al momento de crear la database, me dice que no he puesto la contraseña pero nunca me la ha pedido. ¿Qué estoy haciendo mal?
![imagen](https://user-images.githubusercontent.com/26396425/55440319-9cb6a800-557d-11e9-9674-afd01046295d.png)

**Comment by LuisFros** [comment]
Yo tuve el mismo problema, tienes que setear tus "environment variables " . 
Si te fijas en el archivo "src\config\database.js", se usa" process.env.VARIABLE"
Esta explicado en la [wiki ](https://github.com/IIC2513-2019-1/syllabus/wiki/Tips)

**Comment by gpvidal** [comment]
Sí! lo que te dice @LuisFros es una muy buena sugerencia! Lo otro, si es un problema de configuración de postgres puedes visitar esta guía: https://medium.com/coding-blocks/creating-user-database-and-adding-access-on-postgresql-8bfcd2f4a91e

Saludos,

**Comment by jvlara** [comment]
Lo pude solucionar pero me costo bastante, ocupe direnv de linux y tuve que modificar un archivo del sistema para que funcionara.
Por lo de postgres no había entendido muy bien como funcionaba pero ahora si, gracias a los dos.

**Comment by malopez16** [comment]
Hola! Para los otros que también tengan problemas con eso: logré solucionarlo usando dotenv, sacado del link que citó @LuisFros de la wiki , y además con un poco del link de @gpvidal para establecer los permisos del usuario establecido en el .env que lee dotenv. Perdí harto rato para terminar cachando la solución. Espero que ojala uds no tengan que perder ese tiempo, así que si necesitan más detalles etiquétenme y les puedo explicar más :)

_Disclaimer: Uso Ubuntu._

**Comment by CristobalHV** [comment]
@malopez16 podrias explicar mas en detalle que hiciste para solucionarlo? estoy tratando de correr la app pero me sigue tirando el problema :/

**Comment by malopez16** [comment]
En qué parte de mi explicación quedaste?  hiciste lo de dotenv?

**Comment by CristobalHV** [comment]
@malopez16 me perdi cuando dijiste que usaste esos links de arriba.

Hice lo de dotenv (apliqué incluso su console.log para ver que efectivamente se cargaban las variables) y a pesar de tener creado el rol de usuario en postgres, me sale el error de que falló la autentificación.

**Comment by joseluishaddad** [comment]
> Lo pude solucionar pero me costo bastante, ocupe direnv de linux y tuve que modificar un archivo del sistema para que funcionara.
> Por lo de postgres no había entendido muy bien como funcionaba pero ahora si, gracias a los dos.
@jvlara podrías contarme que hiciste específicamente para lograr que funcionara porfa?

**Comment by jvlara** [comment]
@joseluishaddad Solo si tienes linux:
Lo primero fue meterme con sudo a postgres con `sudo -u postgres psql`
Ahí cree la base de datos que ocupara la app `createdb iic2513template_dev`
También cambiale el password a postgres (que despues tendras que poner en una variable de entorno).
Te sales de postgres con ctrl+z y instalas direnv  con `sudo apt install direnv`
Ahora tienes que modificar un archivo del sistema, que deberia estar oculto (~/.bashrc) en tu carpeta personal
A ese archivo escribes al final `eval "$(direnv hook bash)"`.
Ahora creas un archivo .envrc dentro de la carpeta del proyecto y ahí tienes que setear todas las variables que estan en src\config\database.js, una era `DB_USERNAME`, el formato en que las tienes que escribir es 
export DB_USERNAME=postgres, en cada linea una variable diferente con export, aquí seteas lo que pusiste en postgres de password.
Ahora abre una terminal y entra a tu carpeta del proyecto y ejecuta `direnv allow`, debería salirte algo que diga que se setearon tus variables.
Ojala no me haya saltado nada, espero te funcione:).

**Comment by vjaguilera** [comment]
Hola! Seguí todos los pasos de @jvlara pero me aparece este error:
![Error](https://user-images.githubusercontent.com/30672967/55760990-d0854800-5a2b-11e9-9447-d05a40373f07.png)
Instalé pg de manera global y en la misma carpeta, cerré la terminal y corri la misma migración. Ayuda porfavor :(
